1 get details by national code behrouz
ArminNrz/school-microservice pull request #9
Opened 2022-03-14 18:49 UTC by Behrouz-atoofi

Issue 1 ( completed )

2022-03-16 15:47 UTC, ArminNrz requested changes
این تسک فقط باید اطلاعات دانش آموز را می گرفتیم و اصلا ارتباطی با موجودیت درس نداشته ایم ولی من ریوو های بیشتری در مورد lesson دیدم و بخاطر همین که کارهای نامرتبت داخلش هست قابل مرج نمی باشد

2022-03-16 15:47 UTC, ArminNrz commented on academic-service/pom.xml
>      <parent>
لطفا به فایل هایی که نیاز نیست دست نزنید

2022-03-16 15:47 UTC, ArminNrz commented on academic-service/src/main/java/com/school/academic/controller/LessonController.java
> +
مشابه کامنت بالا

2022-03-16 15:47 UTC, ArminNrz commented on academic-service/src/main/java/com/school/academic/domain/UnitStudent.java
> +}, uniqueConstraints = {
به کلاس هایی که نیاز به تغییر ندارند لطفا دست نزنید ریوو سخت می شود

2022-03-16 15:47 UTC, ArminNrz commented on academic-service/src/main/java/com/school/academic/dto/unit/lesson/UnitLessonBaseDTO.java
> +public class UnitLessonBaseDTO {
نیازی به ساخت این کلاس نیست در این تسک

2022-03-16 15:47 UTC, ArminNrz commented on academic-service/src/main/java/com/school/academic/repository/UnitRepository.java
> +    StudentUnitPointSum countStudentUnitPoint(@Param("studentId") Long StudentId);
متد هایی که اصلا به این ایشو ربطی ندارند

2022-03-16 15:47 UTC, ArminNrz commented on academic-service/src/main/java/com/school/academic/service/highlevel/StudentGetDetails.java
> +        dto.setFirstName(studentDto.getFirstName());
چرا از mapper اسفاده نکردی؟

2022-03-17 05:28 UTC, Behrouz-atoofi commented on academic-service/src/main/java/com/school/academic/dto/unit/lesson/UnitLessonBaseDTO.java
> +public class UnitLessonBaseDTO {
آرمین جان نمیدونم اینا تغییرات قبلی ان که برای این ایشو اومده اینجا

2022-03-17 05:29 UTC, Behrouz-atoofi commented on academic-service/src/main/java/com/school/academic/service/highlevel/StudentGetDetails.java
> +        dto.setFirstName(studentDto.getFirstName());
درسته

2022-03-17 05:29 UTC, Behrouz-atoofi commented
همه این تغییرات رو اعمال میکنم و دوباره پوش میکنم البته یک سری متد و کلاس اضافه کردم برای ایشو بعدی

2022-03-17 20:23 UTC, closed without merging